{
 "title": "容器仓库监控",
 "tags": [
  "docker",
  "registry",
  "internals"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "query_result(registry_http_in_flight_requests)"
   },
   {
    "name": "app",
    "query": "query_result(registry_http_in_flight_requests{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "query": "query_result(up{app=\"$app\"})"
   }
  ]
 },
 "panels": [
  { "title": "常规计数器，CPU，内存和文件描述符统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "启动时间",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"$app\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "缓存请求总数",
   "type": "singlestat",
   "description": "The number of cache request received",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "registry_storage_cache_total{instance=\"$instance\",type=\"Request\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "总命中缓存请求",
   "type": "singlestat",
   "description": "The number of cache request received (hits)",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "registry_storage_cache_total{instance=\"$instance\",type=\"Hit\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "未命中的缓存请求总数",
   "type": "singlestat",
   "description": "The number of cache request received (miss)",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "registry_storage_cache_total{instance=\"$instance\",type=\"Miss\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "常驻内存使用率",
   "type": "singlestat",
   "description": "Process Resident Memory Usage",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "平均CPU使用率",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "平均内存使用率",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "打开文件描述符数",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "仓库指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP请求",
   "type": "graph",
   "description": "The HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(registry_http_requests_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "进行中的HTTP请求",
   "type": "graph",
   "description": "The in-flight HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registry_http_in_flight_requests{instance=\"$instance\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "仓库缓存请求率",
   "type": "graph",
   "description": "The rate of registry cache requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(registry_storage_cache_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "仓库活动延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(registry_storage_action_seconds_sum{instance=\"$instance\"}[2m]) * 1000",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "HTTP请求延迟（秒）（blob）",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob\"}[10m])"
    }
   ]
  },
  {
   "title": "上传HTTP请求延迟（秒）（base）",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"base\"}[10m])"
    }
   ]
  },
  {
   "title": "数秒内上传HTTP请求延迟（blob_upload）",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload\"}[10m])"
    }
   ]
  },
  {
   "title": "HTTP请求延迟（秒）（Manifest）",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"manifest\"}[10m])"
    }
   ]
  },
  {
   "title": "HTTP请求延迟（秒）（catalog）",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"catalog\"}[10m])"
    }
   ]
  }
 ]
}