groups:
- name: 节点告警
  rules:
  - alert: 节点高CPU使用率
    expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[1m]) * ON(instance) GROUP_LEFT(node_name) node_meta * 100) BY (node_name)) > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      description: 节点 {{ $labels.node_name }} CPU使用率为 {{ humanize $value}}%。

  - alert: 节点高内存使用率
    expr: sum(((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * ON(instance) GROUP_LEFT(node_name) node_meta * 100) BY (node_name) > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      description: 节点 {{ $labels.node_name }} 内存使用率为 {{ humanize $value}}%。

  - alert: 节点根分区高使用率
    expr: ((node_filesystem_size_bytes{mountpoint="/rootfs"} - node_filesystem_free_bytes{mountpoint="/rootfs"}) * 100 / node_filesystem_size_bytes{mountpoint="/rootfs"}) * ON(instance) GROUP_LEFT(node_name) node_meta > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      description: 节点 {{ $labels.node_name }} 根分区使用率为 {{ humanize $value}}%。

  - alert: 节点根分区6小时高填充率
    expr: predict_linear(node_filesystem_free_bytes{mountpoint="/rootfs"}[1h], 6 * 3600) * ON(instance) GROUP_LEFT(node_name) node_meta < 0
    for: 1h
    labels:
      severity: critical
    annotations:
      description: 节点 {{ $labels.node_name }} 根分区6小时后将被填满。
