version: '3.8'

networks:
  app_net:
    external: true
    name: test

configs:
  app_config_v1:
    file: ./config.yaml

services:
  testapp:
    image: 172.28.16.155:5000/test/testapp:0.0.1
    ports:
      - 30080:80
    networks:
      - app_net
    configs:
      - source: app_config_v1
        target: /app/configs/config.yaml
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: '1'
        reservations:
          memory: 128M
          cpus: '0.5'
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost/healthz || exit 1"]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 40s
