global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'Test'
    env: 'test'

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

#  - job_name: 'file_ds'
#    file_sd_configs:
#    - refresh_interval: 2m
#      files:
#      - targets.json
#
#  - job_name: 'blackbox_tcp_probe'
#    metrics_path: /probe
#    params:
#      module: [tcp_connect]
#    static_configs:
#      - targets:
#        - 192.168.2.58:2049
#        labels:
#          job: 'nfs-server'
#      - targets:
#        - 192.168.2.58:111
#        labels:
#          job: 'rpcbind'
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: 192.168.2.58:9115
#
#  - job_name: 'blackbox_http_probe'
#    metrics_path: /probe
#    params:
#      module: [http_2xx]
#    static_configs:
#      - targets:
#        - http://mes_app_base_web/healthz
#        - http://mes_app_common_api/healthz
#        - http://mes_app_common_web/
#        - http://mes_app_maintain_api/healthz
#        - http://mes_app_maintain_web/healthz
#        - http://mes_app_materiel_api/healthz
#        - http://mes_app_materiel_web/healthz
#        - http://mes_app_monitor_api/healthz
#        - http://mes_app_monitor_web/healthz
#        - http://mes_app_polishing_section_api/healthz
#        - http://mes_app_polishing_section_web/healthz
#        - http://mes_app_privilege_api/healthz
#        - http://mes_app_privilege_web/healthz
#        - http://mes_app_product_classes_api/healthz
#        - http://mes_app_product_classes_web/healthz
#        - http://mes_app_product_inspection_api/healthz
#        - http://mes_app_product_inspection_web/healthz
#        - http://mes_app_product_order_foam_api/healthz
#        - http://mes_app_product_order_foam_web/healthz
#        - http://mes_app_product_plan_foam_api/healthz
#        - http://mes_app_product_plan_foam_web/healthz
#        - http://mes_app_stock_api/healthz
#        - http://mes_app_stock_web/healthz
#        - http://mes_app_work_schedule_foam_api/healthz
#        - http://mes_app_work_schedule_foam_web/healthz
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - source_labels: [__param_target]
#        target_label: job
#        regex: http[s]?:\/\/(.*)\/.*
#        replacement: $1
#        action: replace
#      - target_label: __address__
#        replacement: 192.168.2.58:9116
